apiVersion: skaffold/v2beta26
kind: Config
build:
  local:
    push: false
#    useDockerCLI: true
  artifacts:
  - image: bert
    context: bert
  - image: ernie
    context: ernie
deploy:
  docker:
    images: [bert, ernie]
